modLoader = "javafml"
loaderVersion = "[${fml},)"
license = "LGPLv3"

issueTrackerURL = "https://github.com/kikugie/elytra-trims/issues"

[[mods]]
modId = "elytratrims"
version = "${version}"
displayName = "Elytra Trims"
displayURL = "https://modrinth.com/mod/elytra-trims"
authors = "KikuGie"
description = '''
Lightweight and customizable support for elytra trims, patterns and dyes
'''
logoFile = "assets/elytratrims/icon.png"

[[mixins]]
config = "elytratrims.mixins.json"

[[dependencies.elytratrims]]
modId = "minecraft"
mandatory = true
versionRange = "${mc}"
ordering = "NONE"
side = "BOTH"